Página para listar todos que contribuem para o desenvolvimento do brasil.io
turicas/brasil.io pull request #139
Opened 2018-08-28 22:33 UTC by juhhcarmona

Criei uma layout inicial para a página de contribuidores de forma que todos que contribuíram para o projeto de alguma forma possam ser listados =). Inicialmente, eu adicionei eu e o @turicas, mas a ideia e ir adicionando o pessoal ou deixar a galera fazer pr.

Para fins demonstrativos eu coloquei duas colunas e ficou dessa forma: 
![captura de tela 2018-08-28 as 19 10 34](https://user-images.githubusercontent.com/1108268/44754596-dc557700-aaf8-11e8-991f-5ecfa7da4e57.png)

e em telas pequenas: 
![captura de tela 2018-08-28 as 19 12 49](https://user-images.githubusercontent.com/1108268/44754624-f2fbce00-aaf8-11e8-9561-233e5166f731.png)

A página atualmente é acessada se clicar no link de contribuidores do rodapé.

Espero que goste!

2018-10-14 03:31 UTC, monteirocamis commented
Oioi  que lindo! Gostaria de ajudar, tem alguma parte que posso fazer? ;)

2018-10-15 11:43 UTC, juhhcarmona commented
Olá @monteirocamis, obrigada por sua disposição =D Nesse PR em particular eu acho que não, da ultima vez que eu falei com o @turicas ele mesmo ficou de inserir os colaboradores na página e por isso o PR não foi merjado ainda. Mas, temos outras coisas que sua ajuda seria muito bem vinda! Você chegou a olhar as outras issues abertas?

2018-10-16 11:16 UTC, turicas requested changes
Muito obrigado! Ficou bem legal. =)
Sugeri duas alterações - qualquer dúvida é só avisar, ok?

2018-10-16 11:16 UTC, turicas commented on core/views.py
> +def contribuidores(request):
O padrão que estamos usando é o nome da view em Inglês e as URLs e texto no site em Português - a ideia é, no futuro, desacoplar as URLs e textos para que outras línguas possam ser facilmente utilizadas (como as views tem mais a ver com funcionalidade da plataforma, faz sentido os nomes estarem em Inglês). Você poderia fazer essa alteração, por favor?

2018-10-16 11:16 UTC, turicas commented on core/views.py
> +    return render(request, 'contribuidores.html', {})
Pensei em atualizarmos diretamente através da API do GitHub, que acha?
A função abaixo retornará [uma lista no mesmo formato da API do GitHub](https://api.github.com/repos/turicas/brasil.io/contributors) e guardará o resultado em memória.

```python
import json
from functools import lru_cache
from urllib.request import urlopen, URLError

@lru_cache()
def contributors(timeout=1):
    try:
        response = urlopen(
            "https://api.github.com/repos/turicas/brasil.io/contributors",
            timeout=timeout
        )
    except URLError:
        return []
    else:
        return json.loads(response.read())
```

Teria que ver como pegar o nome da pessoa e foto (se precisar fazer mais requisições, acho que pode usar só o nome de usuário mesmo).
Que acha?

2018-10-16 13:43 UTC, juhhcarmona commented on core/views.py
> +    return render(request, 'contribuidores.html', {})
Álvaro, mas ai vai ficar só quem contribuiu pelo git, e a ideia era mostrar todos que ajudaram de alguma forma, mesmo que não tenha sido por código... mas sim, pegar a galera do código posso fazer usando isso, mas tem que inserir as outras pessoas também.

2018-10-21 04:06 UTC, turicas commented
Fiz algumas modificações para incluir a sugestão de pegar da API do GitHub, daí podemos melhorá-la no futuro (é melhor ter online a lista de quem já contribuiu só com código do que não tê-la). Está disponível em:

2018-10-21 04:07 UTC, turicas commented
Merge feito em 1084dcf32ac59932d4d64a5255a4abc061d7d776.

2018-10-21 04:07 UTC, closed without merging