Páginas 404 e 500 customizadas
turicas/brasil.io pull request #147
Opened 2018-10-14 00:42 UTC by jessicapaz

close: #93

2018-10-15 11:34 UTC, juhhcarmona commented on core/views.py
> -        # return HttpResponseBadRequest(f'Table does not exist.', status=404)
Olá Jessica! você poderia remover a linha comentada por favor? :D Obrigada!

2018-10-15 11:35 UTC, juhhcarmona commented on core/views.py
> +        # return HttpResponseBadRequest(f'Table does not exist.', status=404)
Você poderia remover a linha comentada aqui também? Muito Obrigada! =D

2018-10-16 11:03 UTC, turicas requested changes
Oi, Jéssica! Obrigado pelo PR. :)
Fiz duas sugestões de alteração - qualquer dúvida é só avisar, ok?

2018-10-16 11:03 UTC, turicas commented on core/templates/404.html
> +        <p>Caso você queira saber mais detalhes,
Você poderia adicionar uma variável opcional aqui, em que através do contexto passado pela view podemos especificar uma frase personalizada para cada página de erro? Assim teremos páginas de erro personalizadas para quando um dataset não é encontrado, uma tabela etc. Essa variável pode ser opcional, algo como: `{% if message %}{{ message }}{% endif %}`.

2018-10-16 11:03 UTC, turicas commented on core/templates/404.html
> +            entre em <a href="{% url 'core:contact' %}">contato.</a></p>
Legal ter colocado o link pra contato! :)

2018-10-16 11:03 UTC, turicas commented on core/views.py
> +        return render(request, '404.html', {})
Existem outros casos de retorno de erro 404 (procure por `HttpResponseBadRequest`, `Http404` e `get_object_or_404` em `core/views.py` e `core/views_special.py`) - você poderia incluir a página de erro 404 que você criou em todos esses casos, por favor?

2018-10-18 20:38 UTC, jessicapaz commented
@turicas Obrigada pelo feedback! Fiz as alterações que você tinha falado, deixei aquela mensagem mais genérica de "página não encontrada" pros casos onde não há mensagem de retorno, como em get_object_or_404. Se tiver qualquer outra sugestão só falar.

2018-11-25 18:38 UTC, merged

2018-11-25 18:39 UTC, turicas commented
@jessicapaz obrigado pelas alterações e desculpe pela demora para revisá-las. Adicionei dois commits ao seu branch (67e8e41eaeaf4ac5c658317d177a239c5abcb1ef e beee21e3358b163d246f38f1940a7ac2227357aa) para resolver conflitos e colocar mais detalhes nos textos das páginas e fiz o merge com `develop`. :)