[Feature] Adiciona Redis Caching
turicas/brasil.io pull request #195
Opened 2020-04-01 02:50 UTC by endoedgar

Esse PR adiciona suporte ao Django-Cachalot para que todas as requisições para as tabelas data_* utilizem do cache antes realizar requisições ao DB.

**É necessário configurar um servidor Redis na variável CACHES do settings.py.**

2020-04-01 05:47 UTC, turicas requested changes

2020-04-01 05:47 UTC, turicas commented on brasilio/settings.py
> +        "LOCATION": "redis://127.0.0.1:6379/1",
Poderia colocar a URI de conexão relativa ao serviço Redis do docker-compose, por favor?

2020-04-01 05:47 UTC, turicas commented on brasilio/settings.py
> +}
Eu não entendi como essa configuração de cache fará cache apenas para as tabelas `data_*` (essa configuração é genérica, vai afetar o banco todo, não?).

2020-04-01 13:36 UTC, endoedgar commented on brasilio/settings.py
> +        "LOCATION": "redis://127.0.0.1:6379/1",
Eu teria que criar um novo serviço para o reddis no docker-composer certo? No momento só temos: 
services:
    db
    graph_db
    mail

2020-04-01 14:04 UTC, endoedgar commented on brasilio/settings.py
> +}
Por padrão o cachalot cacheia todos as operações SQL de ORM do django.
Vou incluir aqui as tabelas não cacheáveis com a constante: CACHALOT_UNCACHABLE_TABLES.

2020-04-01 14:05 UTC, endoedgar commented on brasilio/settings.py
> +}
CACHALOT_UNCACHABLE_TABLES includio no commit 0ba4df3e963377b1316f4f2ae19eba5051248084

2020-04-01 14:05 UTC, turicas commented on brasilio/settings.py
> +        "LOCATION": "redis://127.0.0.1:6379/1",
Sim. Seguir o padrão das portas que estão lá e mudar para pegar a variável de ambiente em vez de ficar hard-coded (como DATABASE_URL).

2020-04-01 14:24 UTC, endoedgar commented on brasilio/settings.py
> +        "LOCATION": "redis://127.0.0.1:6379/1",
OK, resolvido no commit 19264f9ecae2d16e0b41927e28a35bf8a34e9686

2020-04-01 15:15 UTC, berinhard requested changes
O PR tá ótimo, mas senti falta do processo de invalidação do cache. Pelo que conversei com o @turicas, isso deveria acontecer sempre após o [processo do `import_data`](https://github.com/turicas/brasil.io/blob/develop/core/management/commands/import_data.py) terminar de rodar. 

No caso, precisaríamos invalidar o cache do objeto `Table` que foi criado. Para isso, te aconselho criar um método dentro deste model, algo que possa ser chamado como `table.invalidate_cache()` e ele internamente saberia fazer isso. O bom de fazer dessa forma é que você consegue testar unitariamente a invalidação do cache e não complexifica ainda mais esse script de importação, já que vai ser só adicionar uma chamada a esse novo método no final.

2020-04-01 15:34 UTC, endoedgar commented
> O PR tá ótimo, mas senti falta do processo de invalidação do cache. Pelo que conversei com o @turicas, isso deveria acontecer sempre após o [processo do `import_data`](https://github.com/turicas/brasil.io/blob/develop/core/management/commands/import_data.py) terminar de rodar.
> 
> No caso, precisaríamos invalidar o cache do objeto `Table` que foi criado. Para isso, te aconselho criar um método dentro deste model, algo que possa ser chamado como `table.invalidate_cache()` e ele internamente saberia fazer isso. O bom de fazer dessa forma é que você consegue testar unitariamente a invalidação do cache e não complexifica ainda mais esse script de importação, já que vai ser só adicionar uma chamada a esse novo método no final.

Resolvido nos commits 9a61e8d23308b19b8b827960987ac94811c06516 597664b714eb589f90eedfd7ba0963ecc196b966

2020-04-02 15:40 UTC, berinhard requested changes

2020-04-02 15:40 UTC, berinhard commented on core/management/commands/import_data.py
> +            table.invalidate_cache()
@endoedgar essa invalidação do cache deveria estar realmente no final do script. Digo isso porque não sei como o `cachalot` vai lidar com cache dos índices ou das opções de `choice` que são populadas no final do script. Então, para ficarmos mais seguros, seria bom mover para o final do script em si.

2020-04-02 15:50 UTC, endoedgar commented on core/management/commands/import_data.py
> +            table.invalidate_cache()
Beleza

2020-04-02 15:52 UTC, endoedgar commented on core/management/commands/import_data.py
> +            table.invalidate_cache()
Colocado o invalidate no final do método handle em aec8736fab4b9500dd1e201c5ce4267f458fe511

2020-04-02 16:25 UTC, turicas requested changes

2020-04-02 16:25 UTC, turicas commented on core/management/commands/import_data.py
> +            table.invalidate_cache()
Na verdade acho que tem que ficar aqui mesmo, senão as funções abaixo podem usar o cache enquanto deveriam usar os dados novos.

2020-04-02 16:29 UTC, turicas requested changes

2020-04-02 16:29 UTC, turicas commented on brasilio/settings.py
> +        "LOCATION": env('CACHE_LOCATION', default="redis://127.0.0.1:39006"),
Por favor, faça algumas alterações:
- Tirar o valor padrão (é pra dar erro caso a pessoa não tenha a variável de ambiente configurada corretamente);
- Colocar a variável `CACHE_LOCATION` no arquivo `.env`, assim todos terão a variável setada quando carregarem o arquivo.

2020-04-02 17:17 UTC, turicas requested changes

2020-04-02 17:17 UTC, turicas commented on core/management/commands/import_data.py
> +        table.invalidate_cache()
Não sei se vc viu meu comentário, mas essa linha precisa voltar para logo depois de importar os dados (e antes de criar os filtros e tal).

2020-04-02 17:20 UTC, turicas commented on brasilio/settings.py
> +        "LOCATION": env('CACHE_LOCATION', default="redis://127.0.0.1:39006"),
Resolvida em 362829e3b22cb9b7ecf317f827ac8e464e7c0855 e 7f742f394b695b378a88214d6c61f9c636871d8d

2020-04-02 17:36 UTC, endoedgar commented on core/management/commands/import_data.py
> +        table.invalidate_cache()
Ok, vou retornar a linha no lugar onde estava.

2020-04-02 17:43 UTC, endoedgar commented on core/management/commands/import_data.py
> +        table.invalidate_cache()
Resolvido em 3b8fb7a65c371c68946c2bc4faaa66330dad74dd

2020-04-02 23:38 UTC, turicas commented
Fiz um rebase, adicionei alguns detalhes e fiz o merge em 9089f83. Obrigado, @endoedgar! :)

2020-04-02 23:38 UTC, closed without merging