add img[alt] and a[title]
turicas/brasil.io pull request #304
Opened 2020-06-08 15:53 UTC by josecatalani

Atribui a propriedade `alt` para as imagens e `title` para links.

Peço por gentileza, que façam uma leitura e opinem minha forma de atribuir os `title` para os links, busquei uma forma mais ativa de indicação: Veja, Acesse, Apoie!... ao invés de apenas replicar o texto do link.

2020-06-24 17:23 UTC, josecatalani commented
@turicas boa tarde!
Alguma ajuda para esse PR ser priorizado?

2020-06-24 22:33 UTC, turicas requested changes
Desculpe a demora, estamos bastante sobrecarregados por aqui. Fiz algumas sugestões de alteração ("do Brasil.IO" em vez de "da Brasil.io", além de estilo de código nos templates Django - usar espaços entre `{{` e `}}`). Ainda preciso que você faça um rebase pois o branch está em conflitos.
Uma dúvida: não entendi a utilidade do "title" em links cujo texto mostra exatamente o mesmo conteúdo, como `<a href="{% url 'covid19:dashboard' %}" title="Ver mais">Ver mais</a>` - existe alguma diferença grande em leitores de tela, indexadores ou algo assim? Achei essa versão bem mais verbosa, com muita informação repetida desnecessariamente.

2020-06-24 22:33 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/user_creation_form.html
> +        <a href="https://t.me/brasil_io" title="Ir ao Telegram da Brasil.io">
```suggestion
        <a href="https://t.me/brasil_io" title="Ir ao Telegram do Brasil.IO">
```

2020-06-24 22:33 UTC, turicas commented on core/templates/base.html
> +          <a href="/" class="brand-logo" title="Ir a home">
```suggestion
          <a href="/" class="brand-logo" title="Ir à página inicial">
```

2020-06-24 22:33 UTC, turicas commented on core/templates/base.html
> +                    <a class="valign-wrapper" href="https://t.me/brasil_io" title="Ir ao Telegram da Brasil.io">
```suggestion
                    <a class="valign-wrapper" href="https://t.me/brasil_io" title="Ir ao Telegram do Brasil.IO">
```

2020-06-24 22:33 UTC, turicas commented on core/templates/contributors.html
> +            <img class="circle responsive-img" src="{{ contributor.avatar_url }}" alt="Imagem de {{ contributor.login}}">
```suggestion
            <img class="circle responsive-img" src="{{ contributor.avatar_url }}" alt="Imagem de {{ contributor.login }}">
```

2020-06-24 22:33 UTC, turicas commented on covid19/templates/volunteers.html
> +        <a href="{{ volunteer.personal_url }}" target="_blank" title="Visitar perfil de {{volunteer.name}}">
```suggestion
        <a href="{{ volunteer.personal_url }}" target="_blank" title="Visitar perfil de {{ volunteer.name }}">
```

2020-06-24 22:33 UTC, turicas commented on covid19/templates/volunteers.html
> +          <img class="circle responsive-img" src="{{ volunteer.avatar_url }}" alt="Imagem de {{volunteer.name}}">
```suggestion
          <img class="circle responsive-img" src="{{ volunteer.avatar_url }}" alt="Imagem de {{ volunteer.name }}">
```

2020-06-24 22:33 UTC, turicas commented on covid19/templates/volunteers.html
> +      <h6> <a href="{{  volunteer.personal_url }}" title="Visitar perfil de {{volunteer.name}}">{{ volunteer.name }}</a> </h6>
```suggestion
      <h6> <a href="{{  volunteer.personal_url }}" title="Visitar perfil de {{ volunteer.name }}">{{ volunteer.name }}</a> </h6>
```

2020-06-24 22:33 UTC, turicas commented on data-server/templates/list.html
> +      <a href="https://brasil.io/" class="brand-logo" title="Ir ao Telegram da Brasil.IO">
```suggestion
      <a href="https://brasil.io/" class="brand-logo" title="Ir ao Telegram do Brasil.IO">
```

2020-06-24 22:33 UTC, turicas commented on data-server/templates/list.html
> +        <img src="https://data.brasil.io/brasilio-static/img/logo/logo_br-io_fundo-escuro.png" style="max-height:40px;margin-left: 20px; margin-top: 10px;" alt="Logo da Brasil.io">
```suggestion
        <img src="https://data.brasil.io/brasilio-static/img/logo/logo_br-io_fundo-escuro.png" style="max-height:40px;margin-left: 20px; margin-top: 10px;" alt="Logo do Brasil.IO">
```

2020-06-25 14:47 UTC, josecatalani commented
> Desculpe a demora, estamos bastante sobrecarregados por aqui. Fiz algumas sugestões de alteração ("do Brasil.IO" em vez de "da Brasil.io", além de estilo de código nos templates Django - usar espaços entre `{{` e `}}`). Ainda preciso que você faça um rebase pois o branch está em conflitos.

Pode deixar, vou revisar os espaços e faço esse rebase.

> Uma dúvida: não entendi a utilidade do "title" em links cujo texto mostra exatamente o mesmo conteúdo, como `<a href="{% url 'covid19:dashboard' %}" title="Ver mais">Ver mais</a>` - existe alguma diferença grande em leitores de tela, indexadores ou algo assim? Achei essa versão bem mais verbosa, com muita informação repetida desnecessariamente.

Você está certíssimo @turicas, eu reavaliei meu conhecimento de [title] e realmente, não é necessária uma redundância, eu tinha o conhecimento errado que esse atributo era bom para acessibilidade (som, leitura e etc), mas o texto dentro do link que importa, e o atributo só com informações que agregam e enriquecem o link. Vou reavaliar.

2020-06-25 14:55 UTC, turicas commented
> Você está certíssimo @turicas, eu reavaliei meu conhecimento de [title] e realmente, não é necessária uma redundância, eu tinha o conhecimento errado que esse atributo era bom para acessibilidade (som, leitura e etc), mas o texto dentro do link que importa, e o atributo só com informações que agregam e enriquecem o link. Vou reavaliar.

Então aguardo as alterações para esses casos e o rebase para reavaliar o PR, ok?

2020-06-25 19:20 UTC, josecatalani commented
Tirei as redundâncias e acredito que deixei apenas títulos que remetem mais a participação da comunidade e fortalecimento do material de leitura!

2020-06-26 18:18 UTC, josecatalani reviewed
Rebase feito, posso fazer um squash para unificar tudo se preferir.

2020-06-29 22:50 UTC, turicas commented
Obrigado! Você poderia fazer um squash e deixar tudo em somente um commit? Como são alterações relativamente pequenas, acho que fica mais intuitivo o histórico do repositório se esses forem juntados em um só.

2020-06-30 18:26 UTC, josecatalani reviewed
Feito!

2020-06-30 19:01 UTC, berinhard approved these changes

2020-06-30 22:19 UTC, merged

2020-06-30 22:19 UTC, turicas commented
Obrigado. :)

2020-07-02 13:24 UTC, josecatalani commented
> Obrigado. :)

Obrigado eu! vamos para as próximas.

Primeiro PR da comunidade.

2020-07-04 21:59 UTC, turicas commented
> Primeiro PR da comunidade.

Parabéns e bem-vindo! :)