Feature/limit csv download
turicas/brasil.io pull request #347
Opened 2020-06-30 17:30 UTC by berinhard

Fixes #344 

@turicas abri esse PR ainda como **WIP** para validarmos a mensagem da tela de 400. Esse PR é um WIP porque ainda falta a parte de [controle do texto do botão no frontend](https://github.com/turicas/brasil.io/issues/344#issuecomment-651908296).

2020-06-30 18:14 UTC, berinhard commented
@turicas já adicionei a variável nova no server:

```
$ dokku config:set --no-restart brasilio-web BLOCKED_AGENTS="Wget,curl,python-requests,Python-urllib"
-----> Setting config vars
       BLOCKED_AGENTS:  Wget,curl,python-requests,Python-urllib
```

2020-06-30 22:29 UTC, turicas requested changes

2020-06-30 22:29 UTC, turicas commented on brasilio/settings.py
> +BLOCKED_AGENTS = env("BLOCKED_AGENTS", default="").split(",")
Aqui é melhor usar `env.list` ou algo do gênero, dado que `"".split(",")` resulta em `[""]`.

2020-06-30 22:29 UTC, turicas commented on brasilio/settings.py
> +    "covid19.apps.Covid19Config",
Não entendi o porquê dessa mudança de ordem.

2020-06-30 22:29 UTC, turicas commented on core/models.py
> +        return qs.apply_ordering(order_by or [""])
Acredito que aqui deveria ser:
```suggestion
        return qs.apply_ordering(order_by or [])
```
Não?

2020-06-30 22:29 UTC, turicas commented on core/templates/400-csv-without-filters.html
> +</p>
No vim: `gg=G` para indentar o código HTML. :)

2020-06-30 22:29 UTC, turicas commented on core/templates/rest_framework/api.html
> +<p>Estamos tendo um volume muito grande de chamadas a API para interagir com datasets completos. Caso você precise manipular volumes muito grandes de dados, baixe o CSV usando os links disponíveis <b
```suggestion
<p>Estamos tendo um volume muito grande de chamadas a API para interagir com datasets completos. Caso você precise manipular volumes muito grandes de dados, baixe o CSV usando os links disponíveis <b><a href="https://brasil.io/datasets/">nos datasets do Brasil.IO</a></b>. Esses links usam nosso servidor de arquivos estáticos e são a maneira mais rápida (e correta) de baixar bases de dados completas.</p>
```

2020-06-30 22:29 UTC, turicas commented on core/templates/rest_framework/api.html
> +<p>Em breve limitaremos o acesso automatizado ao site, dados esses abusos que vem acontecendo. Peço que acompanhe nossas novidades no <b><a href="https://t.me/brasil_io">Telegram</a></b>.</p>
```suggestion
<p>Em breve limitaremos o acesso automatizado ao site, dados esses abusos que vem acontecendo. Peço que acompanhe as novidades em <a href="https://t.me/brasil_io">nosso canal no Telegram</a>.</p>
```

2020-06-30 22:42 UTC, turicas approved these changes
Estou aprovando com as sugestões que fiz, para fazer o merge e deploy, mas seria legal endereçar o que comentei e ainda não alterei.

2020-06-30 22:42 UTC, turicas commented on core/models.py
> +            qs = qs.search(search_query)
Não entendi bem por que a ordem do filtro/busca foi alterada - foi sem querer ou teve algum motivo em especial? Se a busca existe, a ordem da busca deve prevalecer e por isso devemos rodar antes o qs.search.

2020-06-30 22:42 UTC, turicas commented on core/models.py
> +            qs = qs.search(search_query)
```suggestion
        if search_query:
            qs = qs.search(search_query)
        if filter_query:
            qs = qs.apply_filters(filter_query)
```

2020-06-30 22:52 UTC, merged

2020-07-01 15:46 UTC, berinhard commented on brasilio/settings.py
> +    "covid19.apps.Covid19Config",
Isso é para que o template `rest_framework/api.html` que customizei para apresentar a mensagem seja enxergado pelo Django. Como a app do `rest_framework` estava listada antes das apps do projeto, a customização do template não estava sendo enxergada pelo Django.

2020-07-01 15:47 UTC, berinhard commented on core/models.py
> +            qs = qs.search(search_query)
Alterei só para manter a ordem dos parâmetros. Mas realmente não pensei por esse lado.