Lista arquivos de dataset via Brasil.io ao invés de seguir usando o data.brasil.io
turicas/brasil.io pull request #412
Opened 2020-09-11 21:26 UTC by berinhard

Fixes #404

2020-09-11 22:29 UTC, turicas requested changes
- Remover `Version.download_url`?
- Como gerar `_meta/list.html` no mirror (script data-server deletado) enquanto não implementarmos esse processo estruturado?

2020-09-11 22:29 UTC, turicas commented on core/models.py
> +    @cached_property
Acho que o cache não pode ser aqui, porque no import_data vamos ter novas tabelas, novo SHA512 etc.
O sha512sum deveria ser calculado no objeto TableFile e aí sim poderia ter cache - esse método não deveria ter cache e só já pegar o valor calculado.

2020-09-11 22:35 UTC, berinhard commented
- Ainda não removeria o `version.download_url` enquanto não tivermos todos os datasets com as páginas de listagem já ativas, ou seja, com todos os `_meta/list.html` forçando o redirect. Acho que funciona como um fallback durante a transição para essa nova rota. Por isso, inclusive, que mantive o `redirect` no caso de termos dados inconsistentes e um dataset com uma tabela sem um arquivo associado à ela;
- Foi mal, não dei conta de que a parte de `mirror` tava lá também. Vou voltar com o código e limitá-lo para rodar **apenas** para atualizações dos mirrors;

2020-09-11 22:36 UTC, turicas commented
> * Ainda não removeria o `version.download_url` enquanto não tivermos todos os datasets com as páginas de listagem já ativas, ou seja, com todos os `_meta/list.html` forçando o redirect. Acho que funciona como um fallback durante a transição para essa nova rota. Por isso, inclusive, que mantive o `redirect` no caso de termos dados inconsistentes e um dataset com uma tabela sem um arquivo associado à ela;

Ok. Cria uma issue com isso detalhado, por favor?

> * Foi mal, não dei conta de que a parte de `mirror` tava lá também. Vou voltar com o código e limitá-lo para rodar **apenas** para atualizações dos mirrors;

Ok!

2020-09-15 15:34 UTC, berinhard commented on core/models.py
> +    @cached_property
O `sha512sum` é um [atributo do objeto `TableFile`](https://github.com/turicas/brasil.io/blob/develop/core/models.py#L565), então ele já está sendo calculado por lá. Então vou só tirar esse cache

2020-09-15 15:52 UTC, berinhard commented
@turicas já atualizei o PR com as alterações e criei a issue #420 para não deixarmos de remover o campo `Version.download_url`

2020-09-15 20:07 UTC, turicas commented
Revisei e aprovei as novas alterações, mas precisa de um rebase/merge porque tem conflito em 3 arquivos.

2020-09-15 20:49 UTC, merged