Introduz fluxo de cadastro em 2-passos
turicas/brasil.io pull request #450
Opened 2020-09-28 21:48 UTC by berinhard

Fixes #433 

Demo em vídeo [aqui](https://www.youtube.com/watch?v=OPTfBMroE2A).

No vídeo eu acabei de mostrar a conta que criei sendo apresentada na listagem da newsletter. Segue o print mostrando ela na listagem:

![Screenshot from 2020-09-28 18-47-55](https://user-images.githubusercontent.com/238223/94489599-23703380-01bb-11eb-9dfb-294b324691a5.png)

2020-09-29 17:48 UTC, turicas requested changes

2020-09-29 17:48 UTC, turicas commented on brasilio/settings.py
> +REGISTRATION_OPEN = env("REGISTRATION_OPEN", cast=bool)
Acho que poderiam ter valores padrão (`7`, `SECRET_KEY`, `True`).

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/activation_complete.html
> +      <p>Pronto! Agora você está liberada para acessar todas as páginas do Brasil.io</p>
```suggestion
      <p>
        Pronto! Sua conta foi ativada e agora você pode acessar todas as páginas do <a href="https://brasil.io/">Brasil.IO</a> (incluindo nossa API). :-)
      </p>
      <p>
        Caso você precise baixar quantidades grandes de dados, por favor opte por <b>baixar os dados completos de cada dataset</b> em vez de utilizar a API ou acessar diretamente a listagem dos dados (basta acessar a página do dataset e clicar em "baixar dados completos").
      </p>
      <p>
        O <a href="https://brasil.io/">Brasil.IO</a> é <b>desenvolvido colaborativamente por voluntários</b>, fica aqui o convite para <a href="{% url "core:collaborate" %}">colaborar com o projeto</a>. :-) Considere também <a href="{% url "core:donate" %}">fazer-nos uma doação</a>.
      </p>
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/emails/activation_email_body.txt
> +Obrigado por se cadastrar no Brasil.io =)
```suggestion
Obrigado por se cadastrar no Brasil.IO! =)
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/emails/activation_email_subject.txt
> +[Brasil.io] Ative sua conta
```suggestion
[Brasil.IO] Ative sua conta
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/registration_closed.html
> +        Fique atento ao nosso <a href="https://t.me/brasil_io">grupo do Telegram</a> que é sempre a principal fonte de atualizações sobre o Brasil.io e suas atualizações.
```suggestion
        Acompanhe nosso <a href="https://t.me/brasil_io">canal no Telegram</a> para saber mais novidades.
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/registration_closed.html
> +      <h4>Ops, estamos fechados para novos cadastros</h4>
```suggestion
      <h4>Ops, estamos fechados para novos cadastros!</h4>
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/registration_closed.html
> +        Infelizmente desativamos temporáriamente o cadastro de novas pessoas por questões técnicas.
```suggestion
        Desativamos temporariamente novos cadastros por questões técnicas.
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/templates/brasilio_auth/registration_complete.html
> +
```suggestion
      <h4>Verifique seu e-mail!</h4>
      <p>
        Enviamos um e-mail com o link para ativar seu cadastro. Acesse seu e-mail e clique no link para começar a desfrutar de tudo que o <a href="https://brasil.io/">Brasil.IO</a> pode te oferecer. :-)
      </p>
      <p>
        O <a href="https://brasil.io/">Brasil.IO</a> é <b>desenvolvido colaborativamente por voluntários</b>, fica aqui o convite para <a href="{% url "core:collaborate" %}">colaborar com o projeto</a>. :-) Considere também <a href="{% url "core:donate" %}">fazer-nos uma doação</a>.
      </p>
```

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/forms.py
> +class UserCreationForm(RegistrationFormUniqueEmail):
Dúvida: essa alteração muda em alguma coisa aquela verificação de username único (que tínhamos feito para caso tenhamos cadastrado "Username" e tentem cadastrar "username" não tenhamos problemas)?

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/urls.py
> +        RegistrationView.as_view(),
O `disable_non_logged_user_cache` não é necessário aqui?

2020-09-29 17:48 UTC, turicas commented on brasilio_auth/tests/test_views.py
> +        assert NewsletterSubscriber.objects.filter(user=user).exists()
Dúvida: o email do usuário é cadastrado na newsletter apenas depois que ele ativar o cadastro? Acredito que esse deva ser o fluxo correto (assim não enviaremos email de newsletter a quem se cadastrou, marcou a checkbox mas não confirmou o email).

2020-09-29 18:06 UTC, berinhard commented on brasilio/settings.py
> +REGISTRATION_OPEN = env("REGISTRATION_OPEN", cast=bool)
Resolvido em 
2226fca

2020-09-29 18:07 UTC, berinhard commented on brasilio_auth/templates/brasilio_auth/emails/activation_email_body.txt
> +Obrigado por se cadastrar no Brasil.io =)
Atualiza typo no corpo do email de ativação de senha

2020-09-29 18:13 UTC, berinhard commented on brasilio_auth/urls.py
> +        RegistrationView.as_view(),
Resolvido em aa3bc2b

2020-09-29 18:16 UTC, berinhard commented on brasilio_auth/tests/test_views.py
> +        assert NewsletterSubscriber.objects.filter(user=user).exists()
No caso, não, o newsletter é criado na hora. Fazer dessa forma vai ser meio rolê porque, em algum lugar, vamos ter que guardar que a pessoa optou pela newsletter e ler essa info após a ativação.

Vou resolver isso criando um manager como `Newsletter.objects.active()` e atualizar o processo de download do CSV dos assinantes para usá-lo.

2020-09-29 18:30 UTC, berinhard commented on brasilio_auth/tests/test_views.py
> +        assert NewsletterSubscriber.objects.filter(user=user).exists()
Resolvido em 4f555c4

2020-09-29 18:38 UTC, berinhard commented
@turicas já apliquei todas as alterações do HTML que você sugeriu e também arrumei os outros pontos. Para facilitar o review, tô mandando prints de todos as páginais com o conteúdo atual:

**Fechado para novos cadastros**
![Screenshot from 2020-09-29 15-34-39](https://user-images.githubusercontent.com/238223/94601310-b23b8980-0269-11eb-8e27-f84aabd8c357.png)

**Solicitação para verificar o email**
![Screenshot from 2020-09-29 15-35-37](https://user-images.githubusercontent.com/238223/94601349-bff10f00-0269-11eb-8822-e9669dbcf4ef.png)

**Email enviado**
![Screenshot from 2020-09-29 15-35-46](https://user-images.githubusercontent.com/238223/94601380-c97a7700-0269-11eb-886c-fb356e849f8b.png)

**Ativação finalizada**
![Screenshot from 2020-09-29 15-36-10](https://user-images.githubusercontent.com/238223/94601399-d1d2b200-0269-11eb-9571-a57d1c630c8a.png)

**Erro na ativação**
![Screenshot from 2020-09-29 15-36-27](https://user-images.githubusercontent.com/238223/94601412-d7c89300-0269-11eb-8c72-30e5ba927fc9.png)

2020-10-01 15:08 UTC, turicas commented on brasilio_auth/forms.py
> +class UserCreationForm(RegistrationFormUniqueEmail):
Ficou faltando só responder essa.

2020-10-01 15:09 UTC, turicas approved these changes
Muito bom! Ficou faltando só responder a questão da verificação do username, mas se estiver ainda sendo checado, pode fazer o merge e deploy. :)

2020-10-01 15:24 UTC, berinhard commented on brasilio_auth/forms.py
> +class UserCreationForm(RegistrationFormUniqueEmail):
Não, não muda nada. Tem [teste unitário](https://github.com/turicas/brasil.io/blob/develop/brasilio_auth/tests/test_forms.py#L100) para isso já que continua passando, inclusive.

2020-10-01 15:24 UTC, berinhard commented
Show vou mergear, fazer o deploy e testar o fluxo pra ver se tá rolando mesmo =)

2020-10-01 15:30 UTC, merged