[WIP] Cria model forms dinâmicos para poder validar inputs de querystring
turicas/brasil.io pull request #455
Opened 2020-09-29 22:22 UTC by berinhard

Fixes #242 

@turicas esse PR ainda está como WIP e prova de conceito de que conseguimos usar os model forms dinâmicos para sanitizar esses input. Como esse caminho mostra que é possível, acho que vale uma refatoração **grande** em como a rota de detalhes de um dataset (da interface web, não da API) renderiza o form e manipula a querystring.

Acho que daria para construir esse form dinâmico fora desse método tão específico em que o coloquei agora. Poderíamos, por exemplo, construílo-na view e usá-lo no template do django para renderizar os inputs/valores selecionados. Eu fiz dessa forma bruta para conseguir validar no ponto mais próximo da filtragem sem me preocupar com muitas integrações. Queria alinhar contigo e ver se você acha que vale a pena seguir o caminho de uma refatoração grande no template.

Apesar do DRF não possui nenhuma API muito explícita como o `modelform_factory` podemos seguir a mesma estratégia por lá também. No DRF vai ser ainda mais fácil porque é simplesmente só levantar a exceção de validação do serializer que ele já dá conta de retornar a resposta 400 com os erros.

2020-10-01 14:49 UTC, turicas commented
Acho que o caminho é esse mesmo, mas não poderíamos colocar esse código em `core/forms.py`?

2020-10-01 15:09 UTC, berinhard commented
Show @turicas! Sim, vou mover isso pro form com certeza. Esse PR era só prova de conceito pra garantir que dava para criar o form.

2020-10-01 21:28 UTC, berinhard commented
@turicas agora esse PR tá liberado para review com a validação rolando tanto no frontend quanto na API. Dá uma assistida [neste vídeo de demo](https://www.youtube.com/watch?v=6VI6mHKQIj4) e diz o que você acha das questões que trago no final dele.

2020-10-02 12:33 UTC, turicas commented
Alguns comentários gerais sobre o vídeo (se puder, cria issue pra endereçá-los? Acho que nem tudo é do escopo desse PR):
- Faz total sentido colocarmos mais detalhes nos metadados da tabela na API, como os choices. Acho que podemos seguir um caminho onde vamos descrever melhor o schema que a tabela está atualmente utilizando, daí podemos ter vários schemas (para fazer o versionamento deles) - mas isso é algo que seria melhor discutirmos para depois definir as alterações que precisarão ser feitas.
- Falando em API, esquecemos também de colocar a URL de download de arquivos de cada tabela depois que implementamos o `/files/` (talvez já funcione por conta do `download_url`, mas acho legal checarmos).
- Com relação aos testes, podemos testar uma instância do form dinâmico: a gente cria um Model com fields específicos durante o teste e inspeciona o formulário criado para ver se está de acordo; não é o ideal, mas pelo menos garantimos que tem algum teste passando pelo fluxo de criação do form/validação, que tal?
- Agora que temos um Form do Django, talvez faça sentido usarmos o [django-filter](https://django-filter.readthedocs.io/en/stable/) em vez do método `apply_filtering` -- eu lembro de ter tentado usá-lo (mas não testei muito) e por algum motivo não funcionou com os modelos dinâmicos para filtragem. Uma das coisas que não temos hoje (e que na minha visão é bastante ruim não termos) são os filtros por faixa (exemplo: datas e números de X a Y, em vez do valor exato X) e o `django-filter` talvez possa ajudar nisso.

2020-10-02 12:37 UTC, turicas commented on core/templates/core/dataset-detail.html
> +              {% endfor %}
Que lindeza deletar código 😍

2020-10-02 12:45 UTC, turicas requested changes

2020-10-02 12:45 UTC, turicas commented on core/views.py
>          "fields": fields,
Talvez algum desses campos (como `fields`) não seja mais necessário no template...

2020-10-02 12:45 UTC, turicas commented on core/forms.py
> +        field_factory = model_field.formfield
Talvez a gente possa/precise fazer um hack aqui (acho melhor criarmos uma issue específica para isso): pelo fato de as datas não estarem entre aspas no dialeto padrão do CSV que utilizamos e importamos, o `pgimport` não as reconhece e, por isso, tive que mudar tudo para texto. Por conta disso, os campos de data quando forem criados no form dinâmico irão parecer como se fossem campos de texto (alguns com choices, outros não). O ideal seria utilizar um widget de data (e provavelmente o Django já faz isso automaticamente caso o campo seja um `DateField` e não um `TextField`).

2020-10-02 12:45 UTC, turicas commented on core/views.py
> +    else:
Acho que o padrão é devolver um status code 200 mesmo quando o formulário está inválido, mas pensando semanticamente, acho que o ideal seria o status code ser 4xx, não? A gente pode devolver o HTML do mesmo jeito que está devolvido, mas como foi um erro do usuário e o site não conseguiu processar totalmente a requisição, acredito que o melhor seria devolver um status code mais adequado (como aconteceria na API).

2020-10-02 12:45 UTC, turicas commented on api/views.py
> +        query, search_query, order_by = Model.objects.parse_querystring(querystring)
Me parece estranho o `parse_querystring` estar dentro do `objects`. Será que não temos um lugar melhor pra ele?

2020-10-02 19:51 UTC, berinhard commented on core/views.py
>          "fields": fields,
Tem razão! Removi em 3140392

2020-10-02 19:54 UTC, berinhard commented on core/forms.py
> +        field_factory = model_field.formfield
Hm, vou dar uma sacada aqui pra ver se rola isso sim. Vou tentar usar o [widget `DateInput`](https://docs.djangoproject.com/en/3.1/ref/forms/widgets/#dateinput)

2020-10-02 19:59 UTC, berinhard commented on core/views.py
> +    else:
Showz

2020-10-02 20:01 UTC, berinhard commented on api/views.py
> +        query, search_query, order_by = Model.objects.parse_querystring(querystring)
Também me pareceu, mas não quis mexer nisso não. Acho que podemos mover o método para ser uma função em `core/filters.py`. O que acha?

2020-10-02 20:15 UTC, berinhard commented
> Faz total sentido colocarmos mais detalhes nos metadados da tabela na API, como os choices. Acho que podemos seguir um caminho onde vamos descrever melhor o schema que a tabela está atualmente utilizando, daí podemos ter vários schemas (para fazer o versionamento deles) - mas isso é algo que seria melhor discutirmos para depois definir as alterações que precisarão ser feitas.

Ao meu ver isso tem um pouco a ver com a issue #440 também, certo? Concordo em reestruturar os schemas para sermos mais versáteis no nosso sistema. Mas você acha que já não vale serializarmos esses dados hoje do jeito que a modelagem está e depois refatorarmos. Eu penso em algo como:

```json
{
    "fields": [
        {
            "name": "date",
            "type": "string"
        },
        {
            "name": "state",
            "type": "string"
        },
        {
            "name": "url",
            "type": "string"
        },
        {
            "name": "notes",
            "type": "string"
        }
    ],
    "filters": {
        "date": {"type": "string", "choices": ["2020-10-01", "2020-09-30"]}
    },
    "name": "boletim",
    "data_url": "http://localhost:8000/api/dataset/covid19/boletim/data/",
    "import_date": "2020-09-27T13:22:41.225767-03:00"
}
```

Acho que, nesse PR atualizar o serializer do endpoint `/api/datasets/covid19/` para apresentar essa informação e criar uma issue nova para criar o endpoint específico.

> Falando em API, esquecemos também de colocar a URL de download de arquivos de cada tabela depois que implementamos o /files/ (talvez já funcione por conta do download_url, mas acho legal checarmos).

Putz, pode crer! Criei a issue #458

> Com relação aos testes, podemos testar uma instância do form dinâmico: a gente cria um Model com fields específicos durante o teste e inspeciona o formulário criado para ver se está de acordo; não é o ideal, mas pelo menos garantimos que tem algum teste passando pelo fluxo de criação do form/validação, que tal?

Show! Vou atualizar o PR com isso então :+1: 

> Agora que temos um Form do Django, talvez faça sentido usarmos o django-filter em vez do método apply_filtering -- eu lembro de ter tentado usá-lo (mas não testei muito) e por algum motivo não funcionou com os modelos dinâmicos para filtragem. Uma das coisas que não temos hoje (e que na minha visão é bastante ruim não termos) são os filtros por faixa (exemplo: datas e números de X a Y, em vez do valor exato X) e o django-filter talvez possa ajudar nisso.

Teria que olhar mais a fundo o `django-filter` para entender como combinar isso. Posso fazer isso depois de terminar de atualizar esse PR e, se for o caso, abrir uma nova issue.

2020-10-02 20:21 UTC, berinhard commented on core/forms.py
> +        field_factory = model_field.formfield
Resolvido em 8bbcf07f50f98ae0d0c6b4b8e055d07e29741fb1

2020-10-02 20:23 UTC, berinhard commented on core/templates/core/dataset-detail.html
> +              {% endfor %}
Aproveitando, removi o template filter que era utilizado só para renderizar o form também. Tá nesse commit d3997a9

2020-10-02 20:23 UTC, berinhard commented on core/views.py
> +    else:
Resolvido em 8bbcf07

2020-10-02 20:29 UTC, berinhard commented on api/views.py
> +        query, search_query, order_by = Model.objects.parse_querystring(querystring)
Resolvido em 3fe930a e c14c1df

2020-10-02 21:23 UTC, berinhard commented on core/forms.py
> +        field_factory = model_field.formfield
É, olhei aqui e não tem como saber se o campo é de data pra além de olhar as choices e ver o formato. Daí criei a issue #459 para dar conta disso em específico.

2020-10-02 21:25 UTC, berinhard commented
@turicas testes adicionados =)

2020-10-02 23:15 UTC, turicas commented
- Schema: talvez possamos usar o formato do datapackage diretamente (criei uma tarefa para discutirmos mais pra frente sobre).
- django-filter: já existe a issue #110, comentei lá sobre
- Talvez tenha faltado teste para o 4xx, não?

2020-10-03 22:10 UTC, turicas commented
Criei a issue #460 para endereçar o teste, vou fazer o merge.

2020-10-03 22:10 UTC, merged