[WIP] Atualiza API para forçar autenticação via token
turicas/brasil.io pull request #464
Opened 2020-10-05 14:14 UTC by berinhard

Fixes #427 

Esse PR é um WIP porque ainda falta adicionar o conteúdo ao HTML de listagem das chaves de uma usuária e adiconar o link do menu. De qualquer forma, já abri o PR pro caso de @turicas querer já opinar sobre o código backend que, em teoria, está 100% pronto.

2020-10-05 20:22 UTC, berinhard commented
@turicas terminei o código todo e tá tudo 99% pronto. Só falta o texto do HTML da listagem de chaves de API. Gravei [este demo da autenticação](https://www.youtube.com/watch?v=xrQ2mw5KPVI) funcionando, inclusive com o feature toggle para ligar/desligar.

2020-10-05 20:54 UTC, berinhard commented
Um snippet que testei localmente aqui:

```python
import requests
token = "83466614b26feb76ab791f8a38790a14b712c7ab"
response = requests.get(
  "http://localhost:8000/api/dataset/covid19/caso/data/", 
  headers={"Authorization": f"Token {token}"}
)
print(response.json()["results"])
```

2020-10-05 21:07 UTC, berinhard commented
Depois de gravar o vídeo eu subi o commit 24a494c que linka para um código Python puro com exemplo de uso da API.

2020-10-06 17:51 UTC, turicas requested changes

2020-10-06 17:51 UTC, turicas commented on api/models.py
> +        return binascii.hexlify(os.urandom(20)).decode()
A chave poderia ser algo que identificasse o usuário (ou parte dela fosse de acordo com o usuário) e, para a parte aleatória, utilizasse o UUID4, dessa forma garantiríamos a unicidade dela. Pensei em algo assim:
```python
import uuid

# [...]

    def generate_key(self):
        random_key = str(uuid.uuid4())
        user_url = f"https://auth.brasil.io/{self.user.username.lower()}/"
        user_random_key = uuid.uuid5(uuid.NAMESPACE_URL, user_url + f"key/{random_key}")
        return str(user_random_key).replace("-", "")
```

A solução acima garante:
- Unicidade: a chance de colisão é muito menor, pois primeiro temos o contexto do usuário, para depois a parte aleatória
- Privacidade: a partir do token unicamente (sem acessar o banco de dados) não se consegue identificar o usuário (a solução atual também garante isso)

Não sei se deveríamos manter a característica da privacidade ou se poderíamos embutir em parte do token alguns caracteres que correspondessem ao usuário diretamente (isso poderia facilitar nossas análises mesmo depois de os tokens serem deletados/expirados). Seria algo nessa linha:

```python
import uuid

# [...]

    def generate_key(self):
        random_key = str(uuid.uuid4())
        user_url = f"https://auth.brasil.io/{self.user.username.lower()}/"
        user_uuid = uuid.uuid5(uuid.NAMESPACE_URL, user_url)
        user_random_key = uuid.uuid5(uuid.NAMESPACE_URL, user_url + f"key/{random_key}")
        return (str(user_uuid) + str(user_random_key)).replace("-", "")
```

2020-10-06 17:51 UTC, turicas commented on api/models.py
> +    key = models.CharField("Key", max_length=40, primary_key=True)
Caso a gente prefira usar UUID, aqui poderia ser `UUIDField`.

2020-10-06 17:51 UTC, turicas commented on brasilio_auth/tests/test_views.py
> +class CreateAPiTokensViewsTests(TestCase):
s/APi/API

2020-10-06 17:51 UTC, turicas commented on brasilio_auth/views.py
> +def create_new_api_token(request):
Não seria melhor essa ação ser feita apenas por um POST?

2020-10-06 17:51 UTC, turicas commented on brasilio_auth/views.py
> +def delete_api_token(request, key):
Acho que o método HTTP aceito aqui deveria ser somente DELETE.

2020-10-06 18:26 UTC, berinhard commented on api/models.py
> +        return binascii.hexlify(os.urandom(20)).decode()
Po, ao meu ver parece um pouco exagerado. Fiz um teste aqui e inseri 1.000.000 de tokens no banco local. Com 1 milhão não tive nenhum caso repetido. Então, como a única questão diferente que ficou é a unicidade, já que ambas as soluções garantem a privacidade, acho mais simples manter o  que já temos. Que é exatamente o [mesmo código do DRF](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L36).

2020-10-06 18:28 UTC, berinhard commented on api/models.py
> +        return binascii.hexlify(os.urandom(20)).decode()
Caso queira reproduzir o código que usei é esse aqui:

```python
from tqdm import tqdm
u = User.objects.get(username='bernardo')
for i in tqdm(range(1000)):
    tokens = []
    for i in range(1000):
        tokens.append(Token(user=u, key=Token.generate_key()))
    Token.objects.bulk_create(tokens)
```

2020-10-06 18:29 UTC, berinhard commented on api/models.py
> +    key = models.CharField("Key", max_length=40, primary_key=True)
Acho mais jogo continuarmos com a formatação sugerida pelo DRF

2020-10-06 18:31 UTC, berinhard commented on brasilio_auth/tests/test_views.py
> +class CreateAPiTokensViewsTests(TestCase):
Resolvido em 5923ecb

2020-10-06 18:46 UTC, berinhard commented on brasilio_auth/views.py
> +def delete_api_token(request, key):
Po vai se chato demais fazer isso. Tem todos os problemas do CSRF e sem contar que vamos perder as mensagens de sucesso/erro. Como tá tudo com teste unitário que garante o funcionamento via GET, podemos criar uma issue para refatorar isso mais a frente pra não bloquear o PR. O que acha?

2020-10-06 19:42 UTC, turicas commented on api/models.py
> +        return binascii.hexlify(os.urandom(20)).decode()
Beleza, de acordo. Dúvida: não daria para termos usado o `Token` direto do DRF, em vez de criar um modelo nosso?

2020-10-06 19:43 UTC, turicas commented on brasilio_auth/views.py
> +def delete_api_token(request, key):
Ok, cria uma issue para refatorar então, por favor? Daí coloca também o POST do `create_new_api_token`.

2020-10-06 21:13 UTC, berinhard commented on brasilio_auth/views.py
> +def delete_api_token(request, key):
Documentado em https://github.com/turicas/brasil.io/issues/467

2020-10-06 21:14 UTC, berinhard commented on api/models.py
> +        return binascii.hexlify(os.urandom(20)).decode()
Não porque o token do DRF tem [a relação de 1 para 1](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L14) com o modelo de user. Como não queremos essa restrição, tive que criar esse modelo próprio.

2020-10-06 23:24 UTC, turicas commented
Acho que para fechar faltou só decidir a questão da documentação do código de exemplo [apontada nesse comentário](https://github.com/turicas/brasil.io/pull/464#commitcomment-43012745) (por mim, poderíamos remover o endpoint de exemplo e só linkar para o gist/repositório).

2020-10-08 18:56 UTC, berinhard commented
@turicas a questão da documentação foi atualizada no commit 35637c3c4d0d032b1f527dc969dbb556921c12b1

Então, acho que já rola de mergearmos

2020-10-09 23:03 UTC, merged