Topic/missing tests
turicas/brasil.io pull request #465
Opened 2020-10-05 22:13 UTC by berinhard

Fixes #460
Fixes #462

Tô abrindo o PR pro branch de api-auth porque é só nele que tinha o terreno preparado para testar os endpoints da API. Preferi fazer isso do que ter o retrabalho de reconfigurar e dps gerenciar os conflitos e tal.

2020-10-06 23:36 UTC, turicas requested changes
Além dos comentários que fiz, será que para a issue #462 não seria interessante fazermos um teste que cria um dataset/table, adiciona dados, chama a view e verifica se o dado é exibido? Acho importante ter o teste da variável faltando (mas da maneira como sugeri, automaticamente), mas como a listagem dos dados é algo central na platafora, acho que compensa também termos um teste cobrindo somente esse caso.

2020-10-06 23:36 UTC, turicas commented on brasilio/test_settings.py
> +TEMPLATE_STRING_IF_INVALID = "%%%Invalid varialbe%%%"  # noqa
Little typo here

2020-10-06 23:36 UTC, turicas commented on core/tests/test_views.py
> +        assert settings.TEMPLATE_STRING_IF_INVALID not in response.content.decode()
Acho que depender de lembrar de colocar os asserts em testes pode levar a muitos erros. Talvez devêssemos ir para uma solução mais automática, [como a proposta nesse comentário](https://stackoverflow.com/a/7854378/1299446).

2020-10-07 18:08 UTC, berinhard commented on brasilio/test_settings.py
> +TEMPLATE_STRING_IF_INVALID = "%%%Invalid varialbe%%%"  # noqa
Resolvido em 96315fc

2020-10-07 18:20 UTC, berinhard commented on core/tests/test_views.py
> +        assert settings.TEMPLATE_STRING_IF_INVALID not in response.content.decode()
Essa abordagem levanta um tanto de erros porque, por exemplo, nosso HTML de `404` é customizado e espera algumas variáveis de 404 opicionais no contexto. Como o Django não ass envia por padrão, **todos** os testes de 404 começam a quebrar. Pra fazê-los passar, teríamos que substituir tudos os `get_object_or_404` pro formatação manual de resposta 404. Sei lá, me parece algo trabalhoso demais pra fazer um hack funcionar.

Outra sugestão é cria uma classe de `TestCase` do projeto que sobrescreva o `assertTemplateUsed` para fazer a garantia das strings também.

2020-10-07 19:25 UTC, turicas commented on core/tests/test_views.py
> +        assert settings.TEMPLATE_STRING_IF_INVALID not in response.content.decode()
Eu só gostaria que fosse algo mais automático e que não precisássemos lembrar a cada vez, entende?

2020-10-07 22:22 UTC, turicas requested changes

2020-10-07 22:22 UTC, turicas commented on core/tests/test_views.py
> +        assert match in context["data"].paginator.object_list
Não seria legal também adicionar um teste para o template? O erro que aconteceu foi que o template estava errado (tentando acessar uma variável que era `None`), não o contexto.

2020-10-08 19:02 UTC, berinhard commented on core/tests/test_views.py
> +        assert match in context["data"].paginator.object_list
Eu acho mais jogo testarmos o contexto mesmo. Do tipo, antes não havia nem teste pra gente conseguir chegar perto disso, hoje já conseguimos! O ideal pra mim é entender o cenário que gerou a variável ser `None` e adicionar um teste unitário para reproduzir.

Acho que vale a pena adicionarmos testes pra **todo** o contexto dessa rota de dados, mas só fico com receio desse PR ficar constantemente travado porque sempre vai ter um cenário a mais pra testar.

2020-10-08 19:03 UTC, berinhard commented on core/tests/test_views.py
> +        assert match in context["data"].paginator.object_list
Ou também podemos ir pra outtra estratégia de teste para essa parte. Levantar um servidor pra fazer web crawling mesmo e garantir os dados presentes. Mas igualmente acho que é outra tarefa/PR.

2020-10-09 19:43 UTC, turicas commented on core/tests/test_views.py
> +        assert match in context["data"].paginator.object_list
#472

2020-10-09 19:43 UTC, merged