[WIP] Organiza metadados de campos
turicas/brasil.io pull request #466
Opened 2020-10-06 18:13 UTC by berinhard

Fixes #440 

@turicas esse PR ainda está com WIP ao meu ver porque gostaria de ouvir um pouco da sua opinião sobre o caminho que estou propondo. Acho que podemos seguir algo similar para o `search`.

2020-10-06 23:19 UTC, turicas requested changes
Além do typo que comentei, alguns pontos:

- Acho que faltou atualizar os comandos `update_fields_from_csv` e `export_fields_to_csv`, não?
- Depois da migração de dados, vamos deletar o `filtering_fields`, certo?
- Como fica o `filtering_fields` (na `Table`) e `frontend_filter` (no `Field`) na API?

2020-10-06 23:19 UTC, turicas commented on core/models.py
> +        return self.frontend_filter().filter(has_choices=True)
Faltou um "s" no `self.frontend_filters()`.

2020-10-07 22:11 UTC, turicas requested changes

2020-10-07 22:11 UTC, turicas commented on core/models.py
> +        return self.search_fields
Agora o `search_fields` pode ser removido e então acessar o `self.field_set.searchable()`, não? (o mesmo vale para filtering)

2020-10-08 19:06 UTC, berinhard commented on core/models.py
> +        return self.search_fields
Sim, faltou eu fundamentar isso um pouco mais. A ideia é remover o `search_fields` e o `filtering` também. Eu só precisei mantê-los para conseguir rodar as migrações de dados. Já tive uns problemas com o Django se embaralhando em migração de dados que se baseiam em campos que migrações futuras deletam (nosso cenário).

Minha ideia é a de deletar os campos e criar essas migrações após termos esse PR em produção e migrações executadas.

2020-10-08 19:11 UTC, berinhard commented
> Como fica o filtering_fields (na Table) e frontend_filter (no Field) na API?

Então, o `filtering_fields` vai sumir. Sobre as informações de metadados na API, considero parte dessa issue #204 (que é minha próxima frente)

2020-10-09 19:46 UTC, turicas commented on core/models.py
> +        return self.frontend_filter().filter(has_choices=True)
Faltou consertar isso daqui, não?

2020-10-09 20:20 UTC, berinhard commented
@turicas resolvi a questão do typo adicionando mais testes também no commit d591047

2020-10-09 21:22 UTC, turicas commented on core/models.py
> +        return self.search_fields
Criei a issue #473 para não esquecermos

2020-10-09 21:39 UTC, merged